### PR TITLE
Added conceptual Face Enhancer based on Iterative Mixing idea

### PR DESCRIPTION
**Pull request by larsupb**
Thought it would be a nice feature to apply iterative mixing for face detailing / enhancement. Maybe you give it a try. Results look quite nice - at least in my test :-)
TY

### CODE REVIEW

**Comment by larsupb** [comment]
it requires facelib so you might not want to merge it into main branch directly :-)

**Comment by ttulttul** [comment]
Very cool! I'll try to take a detailed look at this today.

**Comment by ttulttul** [comment]
Could you amend your patch with an example JSON in the examples folder?

**Comment by larsupb** [comment]
I've added an example. However, this technique is especially strong when the model is patched with additional LoRAs. In my experience LoRAs often cover up model details. Outputs are blurry and lack of details. With your technique those details can be brought back into play. Even for characters / faces.

**Comment by larsupb** [comment]
I bet adding Perlin Noise would further improve this effect. BTW: your recent changes on that are great!

**Comment by ttulttul** [comment]
I'm really stoked to check out your changes and I am sorry it's taking me so long to do so. Please feel free to continue working on your fork. I would love to merge this in once I understand it better.

**Comment by ttulttul** [comment]
Hey @larsupb. I'm sorry I never got a chance to approve your PR. I think you should create a custom node in your own repo for this excellent work. I'll keep the interface for my sampler nodes reliably constant to avoid creating incompatibilities.

**Pull request closed without merging**
